language: elixir
matrix:
  include:
    - otp_release: 22.0
      elixir: 1.7.4
    - otp_release: 22.0
      elixir: 1.8.0
    - otp_release: 22.0
      elixir: 1.9
    - otp_release: 22.0
      elixir: 1.10
before_script:
  - MIX_ENV=test mix compile --warnings-as-errors

addons:
  # jsonb support
  postgresql: "9.6"

cache:
  directories:
    - ~/.mix
    - ~/.hex
    - _build
